name: 1.1$(Rev:.r)

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.5'
  displayName: 'Use Python 3.5'

- script: |
    python -m pip install --upgrade pip setuptools twine wheel
    pip install -r requirements.txt
  displayName: 'Install dependencies'

- script: |
    python setup.py sdist bdist_wheel
  displayName: 'Build package'

- task: TwineAuthenticate@1
  inputs:
    pythonUploadServiceConnection: 'PyPI production'
  displayName: 'Authenticate to PyPI'

- script: |
    python -m pip install twine
    python -m twine upload -r pypi --config-file $(PYPIRC_PATH) dist/*
  displayName: 'Upload to PyPI'